### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by edysegura** [edgarw11/logistic-web-app#3]
It would be nice to have some instructions in **README.md** to explain how to use the API's you have implemented.

![image](https://cloud.githubusercontent.com/assets/5324414/10883684/c4728620-815a-11e5-8e15-3c6e2c08000f.png)

**Comment by edysegura** [comment]
Hi @edgarw11!

Is there any documentation of the API's you have implemented? So I don't need guess to test them.

**Comment by edgarw11** [comment]
Hi @edysegura ,

I'm sorry about that. I've tried to use an automated doc generation tool, but I couldn't make it work on time.
I've just added a README file to the repostitory with the use instructions.

**Comment by edysegura** [comment]
Thank you @edgarw11!
