### ISSUE TITLE
API response

### ISSUE THREAD

**Issue by edysegura** [edgarw11/logistic-web-app#5]
Hi @edgarw11!

We usually use a JSON or XML as a response in REST API call.

![image](https://cloud.githubusercontent.com/assets/5324414/11022413/716295d4-8645-11e5-8c33-768c6d003dfd.png)

**Comment by edgarw11** [comment]
Hi @edysegura,

Actually, the application is prepared to respond with HTML or JSON, is just a matter of asking on the Headers for the desired type.
The HTML response is intended for the test web pages that I've created using Jade.
See for example this post request where I asked for a JSON response and correctly received it:

![logistic_json_response](https://cloud.githubusercontent.com/assets/12370997/11034309/c2ba1d80-86d1-11e5-8563-fff73936a178.png)

**Comment by edysegura** [comment]
That highlight is about response. But I got it. Thanks to let me know I've missed that in your README.MD
